Contact/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError, Email
import re


def character_check(form, field):
    # checks that first name/last name are valid
    # no special chars
    excluded_chars = "*?!'^+%&/()=}][{$#@<>"
    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(
                f"Character {char} is not allowed!")


def phone_check(form, field):
    # checks phone number is valid format
    p = re.compile(r'\+?\d{10}')
    if not p.match(field.data):
        raise ValidationError(f'Phone number must be in format +XXXXXXXXXX!')


class ContactForm(FlaskForm):
    email = StringField(validators=[DataRequired(), Email()])
    firstname = StringField(validators=[DataRequired(), character_check])
    lastname = StringField(validators=[DataRequired(), character_check])
    telephone = StringField(validators=[DataRequired(), phone_check])
    message = TextAreaField(validators=[DataRequired(), Length(max=500)])
    submit = SubmitField(validators=[DataRequired()])

Shop/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length, email_validator, ValidationError

def character_check(form, field):
    # checks that first name/last name are valid
    # no special chars
    excluded_chars = "*?!'^+%&/()=}][{$#@<>"
    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(
                f"Character {char} is not allowed!")


class CheckoutForm(FlaskForm):
    email = StringField(validators=[DataRequired()])
    firstname = StringField(validators=[DataRequired(), character_check])
    lastname = StringField(validators=[DataRequired(), character_check])
    address_line1 = StringField(validators=[DataRequired()])
    address_line2 = StringField(validators=[DataRequired()])
    city = StringField(validators=[DataRequired()])
    postcode = StringField(validators=[DataRequired()])
    country = StringField(validators=[DataRequired()])
    submit = SubmitField(validators=[DataRequired()])

Contact/views.py
from flask import Blueprint, render_template, flash
from Contact.forms import ContactForm
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from Contact.email_secrets import *

contact_blueprint = Blueprint('contact', __name__, template_folder='templates')


def insert_into_template(email, message, rep_name, tel):
    return """<html>
              <body>
                <p>You have a new message from """ + email + """,
                   <br>
                   <div>
                   """ + message + """
                   </div>

                   Telephone: """ + tel + """
                   <br>
                   DO NOT RESPOND TO THIS EMAIL. THIS MAILBOX IS UNMONITORED 
                </p>
              </body>
            </html>"""


def generate_message(email, firstname, lastname, tel, u_message):
    message = MIMEMultipart("alternative")
    message["Subject"] = "NEW WEBSITE MAIL: " + firstname + " " + lastname
    message["From"] = email
    message["To"] = recv_email
    html = insert_into_template(email, u_message, tel)
    message.attach(MIMEText(html, "html"))
    return message


def send_mail(form):
    message = generate_message(form.email.data, form.firstname.data,
                               form.lastname.data, form.telephone.data,
                               form.message.data)

    context = ssl.create_default_context()
    try:
        server = smtplib.SMTP(smtp_server, port)
        server.ehlo()  # Can be omitted
        server.starttls(context=context)  # Secure the connection
        server.ehlo()  # Can be omitted
        server.login(sender_email, sender_pswd)
        server.sendmail(sender_email, recv_email, message.as_string())
        server.quit()
        return True
    except Exception as e:
        print(e)
        # Print any error messages to stdout
        return False


@contact_blueprint.route('/contact', methods=['POST', 'GET'])
def contact_form():
    form = ContactForm()
    if form.validate_on_submit():
        if send_mail(form):
            return render_template("index.html")
        else:
            flash("Email could not be sent, please try again")
        # then send email
    return render_template("contact.html", form=form)

Gallery/views.py
from flask import Blueprint, render_template
import os

import random
from exif import Image

gallery_blueprint = Blueprint('gallery', __name__, template_folder='templates')


@gallery_blueprint.route('/gallery')
def gallery():
    return render_template("gallery.html", get_image_set=get_image_set)


def get_meta(path):
    with open(path, 'rb') as image_file:
        my_image = Image(image_file)
        if my_image.has_exif:
            return {"make":my_image.make, "model":my_image.model, "datetime": my_image.datetime_original}


def get_image_set():
    image_set = []
    static = "./static/assets/gallery"
    files = os.listdir(static)
    assets_path = "assets/gallery"
    random.shuffle(files)
    for x in range(len(files)):
        img_path = files[x]
        if img_path == ".DS_Store":
            continue
        # print(img_path)
        p = os.path.join(assets_path, img_path)
        print(p)
        meta = get_meta('static/'+p)
        # print(meta)
        image_set.append({'path': p, 'name': get_image_name(p), 'description': None, "meta" : meta})
        # TODO: implement this so that description gets shop metadata
    return image_set


def get_image_name(path):
    return path.split("/")[-1]

Shop/views.py
from flask import Blueprint, render_template, request, flash
from app import db
from models import Products
from Shop.forms import CheckoutForm

shop_blueprint = Blueprint('shop', __name__, template_folder='templates')

# def get_item_info():
#     imgs = []
#     path = "./static/assets/shop"
#     items = os.listdir(path)
#     assets_path = "assets/shop"
#     for item in items:
#         if item == ".DS_Store":
#             continue
#         f_path = os.path.join(path, item)
#         a_path = os.path.join(assets_path, item)
#         img_paths = os.listdir(f_path)
#         for x in img_paths:
#             imgs.append({'path': os.path.join(a_path, x), 'name': get_image_name(x), 'description': None, 'cost': None})
#     return imgs

@shop_blueprint.route('/shop')
def shop():
    return render_template("shop.html", get_shop_images=get_all_items)


@shop_blueprint.route('/product', methods=['GET', 'POST'])
def product_page():
    pid = request.args.get("prod")
    if pid == None:
        return render_template("error/500.html")
    return render_template("product_page.html", product=get_product(pid))

#
# @shop_blueprint.route('/checkout', methods=['POST'])
# def checkout():
#     form = CheckoutForm()
#     size = [item for key, item in request.form.items()]
#     pid = request.args.get("pid", type=int)
#     product = get_product(pid)
#     if not size:
#         flash("You must choose a size!")
#         return render_template("product_page.html", product=product)
#     else:
#         return render_template("checkout.html", item={'size': size[0], 'product':product}, form=form)

# @shop_blueprint.route("/success", methods=['POST'])
# def submit_checkout():
#     if form.validate_on_submit():
#         flash("Form Submitted!")
#         return render_template("checkout.html", item={'size': size[0], 'product':product}, form=form)

def get_product(pid):
    p = Products.query.filter_by(product_id=pid).first()
    return p


def get_all_items():
    d = []
    results = db.session.query(Products.product_id, Products.image_path, Products.name,
                               Products.colour, Products.cost,
                               Products.description).all()

    for row in results:
        if row.image_path == None:
            continue
        print(row.image_path)
        d.append(
            {'product_id': row.product_id, 'path': row.image_path, 'name': row.name,
             'colour': row.colour,
             'description': row.description, 'cost': str(row.cost) + "0"})
    return d


def get_image_name(path):
    return path.split("/")[-1].split(".")[0]

templates/base.html
<!DOCTYPE html>
<html lang="EN">

<head>
    <link rel="icon" type="image/x-icon" href="/static/assets/img/favicon_icons/favicon.ico"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lost Bond Project</title>
    <link rel="stylesheet" href="../static/Stylesheet.css" />
</head>
        <nav>

            {% if is_home == True %}
            <div class="navbar-home">
                    <a href={{ url_for("index") }} class="navbar-item-home-logo">
                        Lost Bond
                    </a>
                    <a href={{ url_for("shop.shop") }} class="navbar-home-item">
                        Shop
                    </a>
                    <a href={{ url_for("gallery.gallery") }} class="navbar-home-item">
                        Gallery
                    </a>
                    <a href={{ url_for("contact.contact_form") }} class="navbar-home-item">
                        Contact Us
                    </a>
            </div>
            {% else %}
              <div class="navbar-default">
                    <a href={{ url_for("index") }} class="navbar-item-logo">
                       Lost Bond
                    </a>

                    <a href={{ url_for("shop.shop") }} class="navbar-item">
                        Shop
                    </a>
                    <a href={{ url_for("gallery.gallery") }} class="navbar-item">
                        Gallery
                    </a>
                    <a href={{ url_for("contact.contact_form") }} class="navbar-item">
                        Contact Us
                    </a>
            </div>
            {% endif %}
        </nav>
        <div class="main">
            {% block content %}
            {% endblock %}
        </div>


</html>

templates/checkout.html
{% extends "base.html" %}
{% block content %}
    <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <h2 class="flash">
      {% for message in messages %}
         {{ message }}
      {% endfor %}
    </h2>
    {% endif %}
    {% endwith %}
    <form method="post">
        <div class="field">
            {{ form.email(class="input", placeholder="Email") }}
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </form>
    </body>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}
{#    <h1 class="title is-1" style="padding-left: 8%; color: white">Coming Soon</h1>#}
    <p class="caption" style="color: #F5F1ED">Stay tuned for more info</p>
    <br>
    <br>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <h2 class="flash" style="color: red; font-weight: bold; font-size: 20px; padding-left: 8%">
      {% for message in messages %}
         {{ message }}
      {% endfor %}
    </h2>
    {% endif %}
    {% endwith %}
    <form class="column is-5 is-offset-4" method="post">
        <div class="field">
                {{ form.firstname(class="control", placeholder="First Name") }}
                <h2 class="flash">
                {% for error in form.firstname.errors %}
                    {{ error }}
                {% endfor %}
                </h2>
        </div>
        <div class="field">
                {{ form.lastname(class="control", placeholder="Last Name") }}
                <h2 class="flash">
                {% for error in form.lastname.errors %}
                    {{ error }}
                {% endfor %}
                </h2>
        </div>
        <div class="field">
            {{ form.csrf_token() }}
            {{ form.email(class="control", type="email", placeholder="Email") }}
            <h2 class="flash">
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
            </h2>
        </div>
        <div class="field">
                {{ form.telephone(class="control", type="tel", placeholder="Telephone") }}
                <h2 class="flash">
                {% for error in form.telephone.errors %}
                    {{ error }}
                {% endfor %}
                </h2>
        </div>
        <div class="field">
            {{ form.message(class="control-text-area", rows="10", placeholder="Message") }}
            <h2 class="flash">
              {% for error in form.message.errors %}
                {{ error }}
              {% endfor %}
            </h2>
        </div>
        <div class="field">
             {{ form.submit(class="b-control", style="width: 50%; height: 60px; background-color: ") }}
        </div>
    </form>
</div>
{% endblock %}

templates/gallery.html
{% extends "base.html" %}

{% block head %}
          <style>
            .notfound {
              background-color: gray;
              font-size: 125%;
            }
          </style>
        {% endblock %}

{% block content %}
        <div class="gallery_wrapper">
            {% with img_info = get_image_set() %}
             {% for i in range(img_info|count) %}
            <div class="gal_item">
                  <a class="gal_item" href={{ url_for('static', filename=img_info[i]['path']) }}>
                    <img src={{ url_for('static', filename=img_info[i]['path']) }} alt={{ img_info[i]['name'] }} class="gal_item">
                <br>
                 <div class="desc">
                     {{ img_info[i]['name'] }}

                 </div>
                  </a>
             </div>
             {% endfor %}
            {% endwith %}
        </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <body class="home">
        <div class="main">
            <div class="home-bar">
{#                His feet hurt; he stepped and stopped and dragged and stopped,<br>#}
{#                young boy sat down, <br>#}
{#                hands buried within each other and looked up. <br>#}
{#                Mouth firm, indignant as children sometimes get,<br>#}
{#                eyes betraying him, as children can't help. <br>#}
{#                Scrawny boy, weathered pressed<br>#}
{#                his manner tended inwards, wrapped around a point half a metre from his chest,<br>#}
{#                        "How much longer?"<br>#}
                <div style="display: inline-block; text-align: center; justify-content: center">
                    <p class="caption" style="font-size: 20px">
                    Our story on youth mental health, expressed through the arts.<br>
                    What's yours?
                    </p>
                    <iframe width="740" height="350"
                            src="https://www.youtube.com/embed/yysGj38sSL4?autoplay=1&mute=1&loop=1&modestbranding=1&start=1&cc_load_policy=1&color=white">
                    </iframe>
                    <label class="video-dropdown">
                        <div class="video-menu-button">
                        about this video
                        </div>
                        <input type="checkbox" class="dd-input" id="test">
                        <ul class="video-menu">
                            <li class="more-info">
                                The Lost Bond Project presents our debut short film “LOST BOND” (written and directed by Harry Boulton, Gabriel Goss and Jude Wakeley).
                            <br>
                                The story is built upon the inherit complexity of human nature and our ability to feel multiple, competing and contradictory emotions, all conveyed through the presence and actions of the ‘Silent Killer’, a character who personifies the dark shadows of a disturbed mind. All in a bid to raise awareness around the topic of youth mental health.
                            <br>
                                We urge you to support our Go Fund Me campaign which aims to raise funds and awareness for the UK’s leading charity fighting for children and young people’s mental health, Young Minds UK.
                            </li>
                        </ul>
                    </label>
                    <br>
                    <div class="home-gallery_wrapper">
                        {% with img_info = get_image_set() %}
                         {% for i in range(3) %}
                        <div class="gal_item">
                              <a class="gal_item" href={{ url_for('static', filename=img_info[i]['path']) }}>
                                <img src={{ url_for('static', filename=img_info[i]['path']) }} alt={{ img_info[i]['name'] }} class="home-gal-item">
                              </a>
                         </div>
                         {% endfor %}
                            <a class="more-pics" href={{ url_for('gallery.gallery') }}>More -></a>
                        {% endwith %}
                    </div>
                    <iframe style="border-radius:12px; padding: 20px"
                        src="https://open.spotify.com/embed/episode/3qvUFXldA1LQLG8uJf8gGc?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture">
                    </iframe>
                </div>
            </div>
        </div>
    </body>
{% endblock %}

templates/product_page.html
{% extends "base.html" %}

<link rel="icon" type="image/icon" href="/static/assets/img/favicon_icons/favicon.ico"/>

{% block content %}
    <body>
    {% with p = product %}
        <h2>
            {{ p.colour+" " +p.name }}
        </h2>
        <div class="product_info">
            <img src="{{ url_for('static', filename=p.image_path)}}" width="400" height="400" class="product_info"/>
            <div class="product_desc">
                    {{ p.description }}
                <br>
                <br>
                <h3>{{ "£"+p.cost|string +"0" }}</h3>
                <br>
                    <div class="sizes">
                    <label class="size-check">S
                      <input name="size" type="radio" class="size-check" value="s">
                    </label>
                    <label class="size-check">M
                      <input name="size" type="radio" class="size-check" value="m">
                    </label>
                    <label class="size-check">L
                      <input name="size" type="radio" class="size-check" value="l">
                    </label>
                    <label class="size-check">XL
                      <input name="size" type="radio" class="size-check" value="xl">
                    </label>
                    </div>
                    <br>
                    <button class="buy-button"> SOLD OUT </button>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <h2 class="flash">
                  {% for message in messages %}
                     {{ message }}
                  {% endfor %}
                </h2>
                {% endif %}
                {% endwith %}
        </div>

        </div>
    {% endwith %}
    </body>

{% endblock %}

templates/shop.html
{% extends "base.html" %}

{% block content %}
        <div class="caption">
            15% of profits will be donated to the Young Minds Charity
        </div>
       <div class="shop_wrapper">
            {% with product_info = get_shop_images() %}
                {% for i in range(15) %}
                    <div class="shop_div">
                        <div class="img_shop_div">
                                <a class="shop-text" href={{ url_for("shop.product_page", prod=product_info[i]['product_id']) }}>
                                    <img src={{ url_for("static", filename=product_info[i]['path']) }} alt="{{ product_info[i].image_path }}" width="300" height="300">
                                <div class="shop-text">
                                    {{ product_info[i]['colour']+" "}}{{ product_info[i]['name'] }}
                                </div>
                                </a>
                        </div>
                    </div>
            {% endfor %}
            {% endwith %}
       </div>
{% endblock %}

templates/splash.html
<!DOCTYPE html>
<html lang="EN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lost Bond Project</title>
    <link rel="stylesheet" href="../static/Stylesheet.css" />
    <link rel="icon" type="image/x-icon" href="/static/assets/img/favicon_icons/favicon.ico"/>
</head>

<html>
        <div class="splash">
          <div class="splash_header">
              <h1 id="title"></h1>
                <script>
                var i = 0;
                var txt = 'Lost Bond.';
                var speed = 200;

                function typeWriter() {
                  if (i < txt.length) {
                    document.getElementById("title").innerHTML += txt.charAt(i);
                    i++;
                    setTimeout(typeWriter, speed);
                  }
                }
                window.onload=typeWriter;
                </script>
          </div>
          <div class="splash_svg">
            <svg width="100%" height="100%">
                <rect width="100%" height="100%" > </rect>
            </svg>
          </div>
          <div class="splash_minimize">
            <svg width="100%" height="100%">
              <rect width="100%" height="100%" > </rect>
            </svg>
          </div>
        </div>
        <div class="text">
            <a href="{{ url_for('index') }}">
                <button type="button"> Enter </button>
            </a>
        </div>
</html>